### ISSUE TITLE
ERRNO2 (File Not Found) when reading password from database (but 'list' works)

### ISSUE THREAD

**Issue by wraeth** [jamesls/python-keepassx#6]
Listing passwords in the database seems to work fine, and getting the password retrieves some details until it attempts to use subprocess.py - it reads some details out of the database then fails:

```
kp -d .ssh/keepassx.kdb -k .ssh/id_rsa get 3a219f52b8df2f443a965b9519d1b947
Password: 

title:     My password
username:  wraeth
url:       https://mypasswordsite.com
notes:     
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/kp", line 7, in <module>
    sys.exit(main())
  File "/usr/lib64/python2.7/site-packages/keepassx/main.py", line 187, in main
    args.run(args)
  File "/usr/lib64/python2.7/site-packages/keepassx/main.py", line 96, in do_get
    clipboard.copy(entry.password)
  File "/usr/lib64/python2.7/site-packages/keepassx/clipboard.py", line 6, in copy
    get_clipboard().copy(text)
  File "/usr/lib64/python2.7/site-packages/keepassx/clipboard.py", line 22, in copy
    process = subprocess.Popen(self.COPY_PROCESS, stdin=subprocess.PIPE)
  File "/usr/lib64/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by jamesls** [comment]
Looks like it's failing when it tries to copy the password to the clipboard.  What platform are you running on?

**Comment by wraeth** [comment]
Currently running Gentoo with the following package versions:
```
dev-python/keepassx-0.1.0
dev-lang/python-{2.7.10,3.3.5,3.4.3}
x11-wm/awesome-3.5.6```

Let me know if you want other details.

Additionally, perhaps the copy-to-clipboard function could be optional (if it isn't already - I haven't noticed an option to disable it)? Presumably this functionality doesn't get triggered when accessing a kdb through the API, but when working on a console (even from within X) I don't necessarily want/need the password copied to the clipboard.

**Comment by lcbiazon** [comment]
This happens when xclip is not installed. It should be mentioned in the README i guess.
